---
- name: Install zsh (Debian-ish)
  apt: name=zsh state=present
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install zsh (RHEL-ish)
  yum: name=zsh state=present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Fedora"

- name: Sync oh-my-zsh (tmp)
  become: no
  synchronize: src=files/oh-my-zsh dest=/var/tmp/

- name: Move oh-my-zsh (/opt)
  command: mv -fv /var/tmp/oh-my-zsh /opt/

- name: Link oh-my-zsh (users)
  become: yes
  become_user: "{{ item }}"
  file: src=/opt/oh-my-zsh dest=~/.oh-my-zsh state=link
  with_items: "{{ ohmyzsh_install_users }}"

- name: Copy .zshrc to $HOME
  become: yes
  become_user: "{{ item }}"
  template:
    src: zshrc.j2
    dest: ~/.zshrc
  with_items: "{{ ohmyzsh_install_users }}"

- name: Change default shell to zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ ohmyzsh_shell_users }}"

