---
- name: Install zsh (and other neccessary packages)
  package: name={{ item }} state=present
  with_items:
    - rsync
    - zsh
    - git

- stat: path="{{ ohmyzsh_installdir }}/"
  register: omz_dir

- name: Sync (included) oh-my-zsh to host
  block:
    - name: Sync oh-my-zsh (ansible host -> local tmp)
      synchronize:
        src: "{{ role_path }}/files/oh-my-zsh/"
        dest: /tmp/.oh-my-zsh-tmp
        delete: yes
        rsync_opts:
          - "--exclude=custom/themes/flazz2.zsh-theme"
          - "--delete-after"
      become: no

    - name: Sync oh-my-zsh (local tmp -> local libexec)
      synchronize:
        src: /tmp/.oh-my-zsh-tmp/
        dest: "{{ ohmyzsh_installdir }}/"
        delete: yes
        archive: no
        owner: no
        group: no
        links: yes
        recursive: yes
        rsync_opts:
          - "--exclude=custom/themes/flazz2.zsh-theme"
          - "--delete-after"
      delegate_to: "{{ inventory_hostname }}"

    - name: Clean up (local tmp)
      file: path=/tmp/.oh-my-zsh-tmp/ state=absent
  when: ohmyzsh_syncmode == "local" and omz_dir.stat.exists == False

- name: Clone oh-my-zsh (github -> local libexec)
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ohmyzsh_installdir }}"
    update: no
  when: ohmyzsh_syncmode == "github"

- name: prepare custom/themes directory
  file:
    path: "{{ ohmyzsh_installdir }}/custom/themes"
    state: directory

- name: Add in customised flazz2 theme
  copy:
    dest: "{{ ohmyzsh_installdir }}/custom/themes/flazz2.zsh-theme"
    src: custom-flazz2.zsh-theme

- name: Link oh-my-zsh (users)
  become: yes
  become_user: "{{ item }}"
  file: src="{{ ohmyzsh_installdir }}" dest=~/.oh-my-zsh state=link
  with_items: "{{ ohmyzsh_install_users }}"

- name: Copy .zshrc to $HOME
  become: yes
  become_user: "{{ item }}"
  template:
    src: zshrc.j2
    dest: ~/.zshrc
  with_items: "{{ ohmyzsh_install_users }}"

- name: Change default shell to zsh (Linux)
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ ohmyzsh_shell_users }}"
  when: ansible_os_family != "FreeBSD"

- name: Change default shell to zsh (FreeBSD)
  user:
    name: "{{ item }}"
    shell: /usr/local/bin/zsh
  with_items: "{{ ohmyzsh_shell_users }}"
  when: ansible_os_family == "FreeBSD"
