---
- name: Install zsh
  package: name=zsh state=latest
  package: name=rsync state=latest

- name: Sync oh-my-zsh (remote -> local tmp)
  become: no
  synchronize:
    src: files/oh-my-zsh
    dest: /tmp/

- name: Sync oh-my-zsh (local tmp -> local libexec)
  synchronize:
    src: /tmp/oh-my-zsh
    dest: /usr/local/libexec/
  delegate_to: "{{ inventory_hostname }}"

- name: Clean up (local tmp)
  file: path=/tmp/oh-my-zsh state=absent

- name: Link oh-my-zsh (users)
  become: yes
  become_user: "{{ item }}"
  file: src=/usr/local/libexec/oh-my-zsh dest=~/.oh-my-zsh state=link
  with_items: "{{ ohmyzsh_install_users }}"

- name: Copy .zshrc to $HOME
  become: yes
  become_user: "{{ item }}"
  template:
    src: zshrc.j2
    dest: ~/.zshrc
  with_items: "{{ ohmyzsh_install_users }}"

- name: Change default shell to zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ ohmyzsh_shell_users }}"

